-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/Rastrigin/Rastrigin_pkg.vhd
-- Created: 2021-07-14 22:58:58
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Rastrigin_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END Rastrigin_pkg;

