-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/Shubert/Approximation_pkg.vhd
-- Created: 2021-07-14 22:59:16
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Approximation_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END Approximation_pkg;

